### ISSUE TITLE
Bug: The error occurs on an Elasticsearch container when initial access

### ISSUE THREAD

**Issue by skomma** [weseek/crowi-plus-docker-compose#8]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 16.04|
|crowi-plus|2.3.2|
|node.js   |6.12.2|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

How to reproduce? (再現手順)
---------------------------

1. `git clone https://github.com/weseek/crowi-plus-docker-compose`
1. `docker-compose up`
1. access to http://localhost:3000/

What happens? (症状)
---------------------

- Elasticsearch container says
```
elasticsearch_1  | [2018-01-08T13:45:02,011][INFO ][o.e.c.m.MetaDataCreateIndexService] [EPpQpzz] [crowi] creating index, cause [api], templates [], shards [5]/[1], mappings [pages, users]
elasticsearch_1  | [2018-01-08T13:45:02,460][WARN ][r.suppressed             ] path: /_bulk, params: {}
elasticsearch_1  | java.lang.NullPointerException: null
elasticsearch_1  |      at org.elasticsearch.action.bulk.BulkRequest.add(BulkRequest.java:318) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.rest.action.document.RestBulkAction.prepareRequest(RestBulkAction.java:95) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:64) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:260) ~[elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:199) [elasticsearch-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:505) [transport-netty4-5.3.2.jar:5.3.2]
elasticsearch_1  |      at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:72) [transport-netty4-5.3.2.jar:5.3.2]
elasticsearch_1  |      at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
elasticsearch_1  |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
elasticsearch_1  |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
elasticsearch_1  |      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
elasticsearch_1  |      at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:63) [transport-netty4-5.3.2.jar:5.3.2]
elasticsearch_1  |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
elasticsearch_1  |      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
elasticsearch_1  |      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) [netty-transport-4.1.7.Final.jar:4.1.7.Final]
elasticsearch_1  |      at org.elasticsearch.http.netty4.cors.Netty4CorsHandler.channelRead(Netty4CorsHandler.java:76) [transport-netty4-5.3.2.jar:5.3.2]
(snip)
```

What is the expected result? (期待される動作)
-------------------------------------------

- no error occurs.

Note
----

- This stacktrace is equal to the below issue?
  - https://github.com/elastic/elasticsearch/issues/25398
  - この問題と同じだった場合は、crowi-plus 本体の改修が必要

**Comment by skomma** [comment]
moved to weseek/crowi-plus#228
